FROM oven/bun:1

WORKDIR /usr/src/app

RUN apt-get update -y && apt-get install -y openssl

ARG DATABASE_URL

COPY ./packages ./packages 
COPY ./bun.lock ./bun.lock
COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json

COPY ./apps/ws ./apps/ws

ENV DATABASE_URL=$DATABASE_URL

RUN bun install
RUN bun run db:generate

EXPOSE 8081

CMD ["bun", "run", "dev:ws"]